### ISSUE TITLE
geckodriver executable needs to be in PATH(while using brut3k1t)

### ISSUE THREAD

**Issue by destroyeramit** [Hackplayers/4nonimizer#28]
Traceback (most recent call last):
  File "brut3k1t.py", line 77, in <module>
    main()
  File "brut3k1t.py", line 70, in main
    w.execute()
  File "/root/brut3k1t/core/web.py", line 42, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/root/brut3k1t/core/web.py", line 51, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by vmotos** [comment]
brut3k1t.py do not belong to 4nonimizer.. wrong app? xD
